channels:
- conda-forge
dependencies:
- python=3.12.8
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - astunparse==1.6.3
  - cloudpickle==3.1.0
  - jinja2==3.1.5
  - numpy==1.26.4
  - optree==0.13.1
  - pandas==2.2.3
  - torch-geometric==2.6.1
  - torch==2.5.1
name: mlflow-env
